// Generated by LiveScript 1.6.0
(function(){
  var Cenario;
  window.Cenario = Cenario = (function(superclass){
    var prototype = extend$((import$(Cenario, superclass).displayName = 'Cenario', Cenario), superclass).prototype, constructor = Cenario;
    function Cenario(gl){
      Cenario.superclass.call(this, gl);
      this.name = "cenario";
      this.pos = [0.0, 0.0, 0.0];
      this.texture = Resources.getTexture(gl, "cenario.png");
      this.shader = Resources.getShader(gl, "default");
      this.mesh = Resources.getMesh(gl, "cenario");
    }
    Cenario.prototype.update = function(){
      return 1 === 1;
    };
    return Cenario;
  }(GameObject));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
