// Generated by LiveScript 1.6.0
(function(){
  var SpriteHUD, HUD;
  SpriteHUD = (function(superclass){
    var prototype = extend$((import$(SpriteHUD, superclass).displayName = 'SpriteHUD', SpriteHUD), superclass).prototype, constructor = SpriteHUD;
    function SpriteHUD(gl, pos){
      SpriteHUD.superclass.call(this, gl, pos);
      this.texture = Resources.getTexture(gl, "doomPistol.png");
      this.anim.xTiles = 3;
      this.anim.yTiles = 2;
      this.anim.anims["Idle"] = [1, 1];
      this.anim.anims["Shot"] = [0, 5];
      this.anim.curAnim = "Shot";
      this.anim.ended = false;
      this.anim.loopAnim = false;
    }
    SpriteHUD.prototype.render = function(projectionMatrix){
      var viewMatrix;
      viewMatrix = mat4.create();
      mat4.identity(viewMatrix);
      return superclass.prototype.render.call(this, viewMatrix, projectionMatrix);
    };
    return SpriteHUD;
  }(Sprite));
  window.HUD = HUD = (function(){
    HUD.displayName = 'HUD';
    var prototype = HUD.prototype, constructor = HUD;
    function HUD(gl){
      this.gl = gl;
      this.gun = new SpriteHUD(gl, [1.2, -2.1, -0.1]);
      this.text = new Text("Puta dor nas costas socorro", "Lucidas Console", [100, 300], 32, "#ffffff", true);
    }
    HUD.prototype.render = function(){
      var orthoProjectionMatrix;
      orthoProjectionMatrix = mat4.create();
      mat4.ortho(orthoProjectionMatrix, -2.0, 2.0, -2.0, 2.0, 0.1, 5.0);
      return this.gun.render(orthoProjectionMatrix);
    };
    return HUD;
  }());
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
