// Generated by LiveScript 1.6.0
(function(){
  var Logo, HUD;
  Logo = (function(superclass){
    var prototype = extend$((import$(Logo, superclass).displayName = 'Logo', Logo), superclass).prototype, constructor = Logo;
    function Logo(gl){
      var pos;
      pos = [1.2, -1.1, -0.1];
      Logo.superclass.call(this, gl, pos);
      this.texture = Resources.getTexture(gl, "logoTV.png");
    }
    return Logo;
  }(SpriteHUD));
  window.HUD = HUD = (function(){
    HUD.displayName = 'HUD';
    var prototype = HUD.prototype, constructor = HUD;
    HUD.damageScreen = void 8;
    function HUD(gl){
      this.gl = gl;
      constructor.damageScreen = document.getElementById("damageScreen");
      this.weapon = new WeaponHud(gl);
      this.logo = new Logo(gl);
    }
    HUD.prototype.render = function(){
      var orthoProjectionMatrix;
      orthoProjectionMatrix = mat4.create();
      mat4.ortho(orthoProjectionMatrix, -2.0, 2.0, -2.0, 2.0, 0.1, 5.0);
      this.logo.render(orthoProjectionMatrix);
      if (!Message.get("isPlayerDead")) {
        return this.weapon.render(orthoProjectionMatrix);
      } else {
        return constructor.damageScreen.style.opacity = 0.25;
      }
    };
    HUD.prototype.update = function(){
      return this.weapon.update();
    };
    return HUD;
  }());
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
