// Generated by LiveScript 1.6.0
(function(){
  var Input;
  window.Input = Input = (function(){
    Input.displayName = 'Input';
    var prototype = Input.prototype, constructor = Input;
    Input.keys = [];
    function Input(){
      window.addEventListener('keydown', this.keydownCallback);
      window.addEventListener('keyup', this.keyupCallback);
    }
    Input.prototype.keydownCallback = function(e){
      return constructor.keys[e.keyCode] = true;
    };
    Input.prototype.keyupCallback = function(e){
      return constructor.keys[e.keyCode] = false;
    };
    return Input;
  }());
}).call(this);
