// Generated by LiveScript 1.6.0
(function(){
  var glsl_scripts, js_scripts, mainScript, i$, len$, f, script, game, render;
  glsl_scripts = ["default"];
  js_scripts = ["shader", "game", "gl-matrix"];
  mainScript = document.getElementById("main_script");
  for (i$ = 0, len$ = glsl_scripts.length; i$ < len$; ++i$) {
    f = glsl_scripts[i$];
    script = document.createElement("SCRIPT");
    script.src = "assets/shaders/" + f + ".vs";
    script.type = "x-shader/x-vertex";
    script.id = f + ".vs";
    document.body.insertBefore(script, document.body.childNodes[0]);
    script = document.createElement("SCRIPT");
    script.src = "assets/shaders/" + f + ".fs";
    script.type = "x-shader/x-fragment";
    script.id = f + ".fs";
    document.body.insertBefore(script, document.body.childNodes[0]);
  }
  game = new Game;
  game.start();
  render = function(){
    game.render();
    game.update();
    return requestAnimationFrame(render);
  };
  render();
}).call(this);
