// Generated by LiveScript 1.6.0
(function(){
  var game, render;
  game = new Game;
  game.start();
  render = function(){
    game.render();
    game.update();
    return requestAnimationFrame(render);
  };
  render();
}).call(this);
