// Generated by LiveScript 1.6.0
(function(){
  var Message;
  window.Message = Message = (function(){
    Message.displayName = 'Message';
    var prototype = Message.prototype, constructor = Message;
    Message.mailbox = {};
    Message.send = function(name, value){
      constructor.mailbox[name] = value;
    };
    Message.get = function(name){
      return constructor.mailbox[name];
    };
    function Message(){}
    return Message;
  }());
}).call(this);
