// Generated by LiveScript 1.6.0
(function(){
  var PaiJimmy;
  window.PaiJimmy = PaiJimmy = (function(superclass){
    var prototype = extend$((import$(PaiJimmy, superclass).displayName = 'PaiJimmy', PaiJimmy), superclass).prototype, constructor = PaiJimmy;
    function PaiJimmy(gl, pos){
      PaiJimmy.superclass.call(this, gl);
      this.name = "paiJimmy";
      this.pos = pos;
      this.texture = Resources.getTexture(gl, "paiJimmy.png");
      this.shader = Resources.getShader(gl, "default");
      this.mesh = Resources.getMesh(gl, "cube");
    }
    PaiJimmy.prototype.update = function(){
      return this.rot[1] += -0.01;
    };
    return PaiJimmy;
  }(GameObject));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
