// Generated by LiveScript 1.6.0
(function(){
  var Player;
  window.Player = Player = (function(){
    Player.displayName = 'Player';
    var MAX_VEL, prototype = Player.prototype, constructor = Player;
    MAX_VEL = 0.2;
    function Player(pos){
      this.pos = pos;
      this.vel = [0.0, 0.0, 0.0];
      this.dir = [0.0, 0.0, 0.0];
      this.radius = 1.0;
      this.height = 2.0;
      this.collidingWith = [];
    }
    Player.prototype.update = function(deltaTime){
      this.updatePosition();
      this.readInput();
      this.calcVel(deltaTime);
      return this.sendMessages();
    };
    Player.prototype.updatePosition = function(){
      vec3.add(this.pos, this.pos, this.vel);
    };
    Player.prototype.calcVel = function(deltaTime){
      var front, right;
      front = vec3.clone(Message.get("cameraFrontVec"));
      right = vec3.clone(Message.get("cameraRightVec"));
      front[1] = 0.0;
      vec3.normalize(front, front);
      vec3.scale(right, right, this.dir[0] * MAX_VEL * deltaTime);
      vec3.scale(front, front, this.dir[2] * MAX_VEL * deltaTime);
      vec3.add(this.vel, front, right);
    };
    Player.prototype.readInput = function(){
      this.dir = [0.0, 0.0, 0.0];
      if (Input.keys[87]) {
        this.dir[2] += 1;
      }
      if (Input.keys[83]) {
        this.dir[2] += -1;
      }
      if (Input.keys[68]) {
        this.dir[0] += 1;
      }
      if (Input.keys[65]) {
        this.dir[0] += -1;
      }
      vec3.normalize(this.dir, this.dir);
    };
    Player.prototype.sendMessages = function(){
      return Message.send("playerPosition", this.pos);
    };
    return Player;
  }());
}).call(this);
