// Generated by LiveScript 1.6.0
(function(){
  var Resources;
  window.Resources = Resources = (function(){
    Resources.displayName = 'Resources';
    var prototype = Resources.prototype, constructor = Resources;
    Resources.meshes = {};
    Resources.textures = {};
    Resources.shaders = {};
    Resources.images = {};
    Resources.audio = {};
    Resources.getMesh = function(gl, name){
      if (this.meshes[name]) {
        return this.meshes[name];
      } else {
        this.meshes[name] = new Mesh(gl, name);
        return this.meshes[name];
      }
    };
    Resources.getTexture = function(gl, name, cubemap){
      cubemap == null && (cubemap = false);
      if (this.textures[name]) {
        return this.textures[name];
      } else {
        this.textures[name] = new Texture(gl, name, cubemap);
        return this.textures[name];
      }
    };
    Resources.getShader = function(gl, name){
      if (this.shaders[name]) {
        return this.shaders[name];
      } else {
        this.shaders[name] = new Shader(gl, name);
        return this.shaders[name];
      }
    };
    Resources.getAudio = function(name){
      var audio;
      if (this.audio[name]) {
        return this.audio[name];
      } else {
        audio = document.createElement("AUDIO");
        audio.src = "assets/audio/" + name;
        this.audio[name] = audio;
        return this.audio[name];
      }
    };
    function Resources(){}
    return Resources;
  }());
}).call(this);
