// Generated by LiveScript 1.6.0
(function(){
  var Skybox;
  window.Skybox = Skybox = (function(superclass){
    var prototype = extend$((import$(Skybox, superclass).displayName = 'Skybox', Skybox), superclass).prototype, constructor = Skybox;
    function Skybox(gl){
      Skybox.superclass.call(this, gl);
      this.name = "skybox";
      this.pos = [0.0, 0.0, 0.0];
      this.texture = Resources.getTexture(gl, "skybox.png");
      this.shader = Resources.getShader(gl, "skybox");
      this.mesh = Resources.getMesh(gl, "skybox");
    }
    Skybox.prototype.update = function(){
      1 === 1;
    };
    return Skybox;
  }(GameObject));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
