// Generated by LiveScript 1.6.0
(function(){
  var Sprite;
  window.Sprite = Sprite = (function(superclass){
    var prototype = extend$((import$(Sprite, superclass).displayName = 'Sprite', Sprite), superclass).prototype, constructor = Sprite;
    function Sprite(gl, pos){
      Sprite.superclass.call(this, gl);
      this.name = "xaropinho";
      this.pos = pos;
      this.anim = {
        xTiles: 2,
        yTiles: 2,
        curFrame: 0,
        curAnim: "Idle"
      };
      this.shader = Resources.getShader(gl, "sprite");
      this.mesh = Resources.getMesh(gl, "sprite1");
    }
    Sprite.prototype.render = function(viewMatrix, projectionMatrix){
      this.setShaderAnimation();
      this.nextFrame();
      return superclass.prototype.render.apply(this, arguments);
    };
    Sprite.prototype.update = function(){
      return 1 === 1;
    };
    Sprite.prototype.setShaderAnimation = function(){
      this.shader.setUniformInt("x_tiles", this.anim.xTiles);
      this.shader.setUniformInt("y_tiles", this.anim.yTiles);
      this.shader.setUniformInt("frame", this.anim.curFrame);
    };
    Sprite.prototype.nextFrame = function(){
      this.anim.curFrame += 1;
    };
    Sprite.prototype.lookAtCamera = function(){
      var camPos, dist;
      camPos = vec3.clone(Message.get("cameraPosition"));
      if (camPos) {
        camPos[1] = 0.0;
        camPos[2] *= -1;
        dist = vec3.sub([0.0, 0.0, 0.0], camPos, this.pos);
        vec3.normalize(dist, dist);
        if (dist[0] > 0.0 && dist[2] > 0.0) {
          this.rot[1] = Math.atan(dist[2] / dist[0]);
        } else if (dist[0] < 0.0 && dist[2] > 0.0) {
          this.rot[1] = Math.PI + Math.atan(dist[2] / dist[0]);
        } else if (dist[0] < 0.0 && dist[2] < 0.0) {
          this.rot[1] = Math.PI + Math.atan(dist[2] / dist[0]);
        } else {
          this.rot[1] = Math.atan(dist[2] / dist[0]);
        }
        this.rot[1] += Math.PI / 2;
      }
    };
    return Sprite;
  }(GameObject));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
