// Generated by LiveScript 1.6.0
(function(){
  var WeaponHud;
  window.WeaponHud = WeaponHud = (function(){
    WeaponHud.displayName = 'WeaponHud';
    var prototype = WeaponHud.prototype, constructor = WeaponHud;
    function WeaponHud(gl){
      this.sprite = new SpriteHUD(gl, [1.2, -1.1, -0.1]);
    }
    WeaponHud.prototype.render = function(projectionMatrix){
      return this.sprite.render(projectionMatrix);
    };
    WeaponHud.prototype.update = function(){
      var cameraPos, cameraDir;
      if (Input.onKeydown(70)) {
        this.sprite.playAnim("Shot", false);
        AudioManager.playSound("tiro.mp3");
        cameraPos = Message.get("cameraPosition");
        cameraDir = Message.get("cameraFrontVec");
        return Collision.raycast(cameraPos, cameraDir, 1);
      }
    };
    return WeaponHud;
  }());
}).call(this);
