// Generated by LiveScript 1.6.0
(function(){
  var Xaropinho;
  window.Xaropinho = Xaropinho = (function(superclass){
    var prototype = extend$((import$(Xaropinho, superclass).displayName = 'Xaropinho', Xaropinho), superclass).prototype, constructor = Xaropinho;
    function Xaropinho(gl, pos){
      Xaropinho.superclass.call(this, gl, pos);
      this.name = "xaropinho";
      this.texture = Resources.getTexture(gl, "xaropinho.png");
      this.shader = Resources.getShader(gl, "sprite");
      this.mesh = Resources.getMesh(gl, "sprite1");
      this.canCollide = true;
      this.anim.xTiles = 1;
      this.anim.yTiles = 1;
    }
    Xaropinho.prototype.update = function(){
      return this.lookAtCamera();
    };
    return Xaropinho;
  }(Sprite));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
